import test from 'node:test';import assert from 'node:assert/strict';import {io as Client} from 'socket.io-client';
process.env.NODE_ENV='test';const {http,rooms}=await import('../server.js');
await new Promise(r=>http.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${http.address().port}`;
const event=(c,n,pred=()=>true)=>new Promise((r,j)=>{const t=setTimeout(()=>{c.off(n,on);j(new Error('timeout '+n))},3000);const on=x=>{if(!pred(x))return;clearTimeout(t);c.off(n,on);r(x)};c.on(n,on)});const ack=(c,n,p)=>new Promise(r=>c.emit(n,p,r));
test('two clients: correct placement keeps card, wrong placement discards it',async()=>{const a=Client(url),b=Client(url);await Promise.all([event(a,'connect'),event(b,'connect')]);const cr=await ack(a,'create',{name:'Moshe'});const joined=event(b,'state');await ack(b,'join',{code:cr.code,name:'Friend'});await joined;a.emit('start');let st=await event(a,'state',x=>x.phase==='playing');assert.equal(st.activePlayerId,a.id);
 a.emit('place',{slot:0});st=await event(a,'state');assert.equal(st.players.find(p=>p.id===a.id).ready,true);a.emit('reveal');st=await event(a,'state');let pa=st.players.find(p=>p.id===a.id);assert.equal(pa.lastResult.correct,true);assert.equal(pa.timeline.length,1);assert.equal(pa.score,1);
 a.emit('next');st=await event(b,'state',x=>x.phase==='playing'&&x.round===2);assert.equal(st.activePlayerId,b.id);const room=rooms.get(cr.code),pb=room.players.get(b.id),answer=room.current.year;pb.timeline=[{year:answer+1,title:'Future card',artist:'Test'}];b.emit('place',{slot:1});st=await event(b,'state');assert.equal(st.players.find(p=>p.id===b.id).ready,true);a.emit('reveal');st=await event(b,'state');const pub=st.players.find(p=>p.id===b.id);assert.equal(pub.lastResult.correct,false);assert.equal(pub.timeline.length,1);assert.equal(pub.timeline[0].title,'Future card');assert.equal(pub.score,0);
 a.disconnect();b.disconnect()});
test.after(()=>new Promise(r=>http.close(r)));
